### PR TITLE
Add pre-commit hook

### PR DESCRIPTION
**Pull request by bdice**
Hi @nschloe, thanks for creating this tool!

I'd like to use this repository as a [pre-commit hook](https://pre-commit.com/), to format changed files on each commit.

According to the developer of pre-commit, tools used with pre-commit should accept multiple files as positional arguments.
- https://github.com/pre-commit/pre-commit/issues/394
- https://github.com/pre-commit/pre-commit/issues/1728

I modified the CLI arguments to support multiple input files when `--in-place` is specified. I tried to ensure that the previous behavior of `[infile] [outfile]` is retained, and added a warning or error that prints to `sys.stderr` whenever invalid combinations of options are provided.

I'm open to your thoughts -- if this is "too breaking" then feel free to reject it and I can just use my fork of the project. I was inspired to do this by another nice TeX tool that has a pre-commit hook: https://github.com/FlamingTempura/bibtex-tidy

Also tagging @s-weigand because I saw they forked this repository and have experience with pre-commit hooks.

### CODE REVIEW

**Comment by s-weigand** [comment]
I was working on the same thing today 🤣 
I tried to keep it backward compatible by only changing the behavior when adding a `--allow-multiple-files` flag.
When I got tests added I will also make a PR maybe we can compare notes ^^

**Comment by bdice** [comment]
@s-weigand Ha! I saw you forked this repo and that got me interested in the tool. Your implementation will probably be “less breaking” — and I haven’t gotten to adding tests. Ping me when you open a PR, happy to collaborate.

**Comment by s-weigand** [comment]
A quick explanation on how `pre-commit`  works and why `.pre-commit-hooks.yaml` needs to be in the repo repo root.
- `pre-commit` first creates a virtual env in `~/.cache/pre-commit` (each hook revision gets its own env)
- then it clones the hook repo and installs it in that virtual env
- to run the hook it looks up `.pre-commit-hooks.yaml` in the hook repo with contains the instructions on how to run it (entrypoint, args, filetype, etc.)

`pre-commit` is a very convenient way to run all your quality assurance tools (linter, formatter, etc.) at once.
If you run `pre-commit install`, it adds a git hook so all configured tools run on the staged files when you try to make a commit and intercepts it if any tool has a non-zero return code.
I'm using it for 1.5 years now and wouldn't want to miss it ^^

**Comment by nschloe** [comment]
Got it, thanks!

**Comment by bdice** [comment]
I rebased this PR so that it contains only the `.pre-commit-hooks.yaml` file. I believe the other changes were no longer needed after #35.

@nschloe Can you allow this PR to run the CI tests? I see a message that says "First-time contributors need a maintainer to approve running workflows."

@s-weigand If you have any comments to add, please feel free!

Thank you both for your input and help. 👍

**Comment by nschloe** [comment]
Merged, thanks!

**Pull request merged**
