### PR TITLE
✨ Add encoding option

### PR DESCRIPTION
**Pull request by s-weigand**
This PR adds: 
- More tests for the cli and non-zero returncode if files changed
- The option to set an (e.g. `-e=utf8`/`--encoding=utf8`)
- A pre-commit config with basic QA tools

### CODE REVIEW

**Comment by s-weigand** [comment]
Looks like the branch protection uses the `name` property of a job to determine which is which and doesn't like my renaming them.

**Comment by nschloe** [comment]
Yeah, probably just start anew?

**Comment by s-weigand** [comment]
I will just remove the `name` property again.

**Comment by nschloe** [comment]
LGTM, thanks!

**Pull request merged**
